### ISSUE TITLE
Silently fails in some terminals

### ISSUE THREAD

**Issue by swalladge** [senorprogrammer/wtf#104]
When I try to run this in Termite or Kitty, it exits immediately with an exit status of 1 and no messages to stdout/stderr. However if I change the value of `TERM` to something well known, like `xterm-256color` or `rxvt-unicode-256color`, it runs fine.

**Comment by Dieterbe** [comment]
+1 same problem with termite (TERM=xterm-termite)

**Comment by senorprogrammer** [comment]
Let me know if this helps things or not: I just committed the ability to set the `TERM` value via the config file. See https://wtfutil.com/posts/configuration/attributes/ for details.

**Comment by Dieterbe** [comment]
this looks strange. there already exists a widely adopted mechanism for the terminal to announce to applications what kind of terminal it is : the `TERM` environment variable.

the workarounds that @swalladge and me are doing are kind of hacks. our terminal capabilities are not the ones we're advertising via $TERM but it works as long as the app only exercises functionality which is common to the running terminal and the one being faked.
the real problem is the app supports more terminals than it thinks it does so it simply needs to accept these less common TERM values.

**Comment by senorprogrammer** [comment]
Yeah, allowing the app to force the terminal type via the config is also a hack. Just a stop-gap until I (or someone) comes up with a way to fix the issues you're seeing properly.

**Comment by senorprogrammer** [comment]
Basically the solution is to force your terminal into a mode supported by [tcell](https://github.com/gdamore/tcell/tree/master/terminfo). WTF is designed to use your $TERM ENV var but if that's set to something that isn't supported, then you'll want to use the config to force it.

From the link above you can see that `xterm-termite` isn't a supported terminfo value.
