### ISSUE TITLE
Multiple instances of the same module?

### ISSUE THREAD

**Issue by rclayton-the-terrible** [senorprogrammer/wtf#111]
Hey, thank you for the great tool!  Maybe I missed something in the documentation, but it seems like you can have only one instance of a module.  Is that correct?  I would definitely love to be able to use `cmdrunner` multiple times to check on the status of Docker and PM2 (and other things).

**Comment by senorprogrammer** [comment]
You're correct, it doesn't support multiple instances of the same module. I thought a lot about that and decided not to support that design for a few reasons:

1. I prefer a single module that supports multiple datasets (i.e. Weather, Github, etc.) because it is designed for important data infrequently needed. A couple times a day I check through Git and GitHub, for instance, to see if I need to take any action, but I don't need to see all of them all the time.

2. I prefer domain-specific modules over generic modules. `CmdRunner` is really a development hack to try out things I might want to create specific modules for (that's how the `Power` came about). In your examples, I'd rather see someone create a dedicated Docker and PM2 module that can be formatted well and displayed in an elegant way.

3. You can run multiple instances of WTF by passing specific config files into it. In theory (I haven't tried this), you could open multiple terminal panes, run a single instance of WTF in each of them, and point those at whatever you like, and get the same effect. It's a hack, but doable.

Regards,
Chris

**Comment by rclayton-the-terrible** [comment]
It's not just `CmdRunner`; I needed the feature for Google Calendar (work and personal) and Git (I want commits from multiple repositories in their own box).  Sure I can run multiple instances, but that's not very convenient if I want to use the tool like a dashboard.

I'm probably going to fork this repository and implement this feature.  I think this feature is so essential that you risk someone else's fork becoming more popular than the original project.

**Comment by senorprogrammer** [comment]
Go nuts @rclayton-the-terrible, I'm not a huge fan of threats and I didn't build this for you, I built it for me. Your entitelment about what you "need" from something you didn't know existed five days ago is says a lot about you.

Fork away and best of luck.

**Comment by rclayton-the-terrible** [comment]
@senorprogrammer - I'm sorry you took my last message as a threat; I did not intend it as so.  My worry was the project becoming fragmented like a number of other open source projects due to disagreements in features/implementation.  So, if I came off like an ass, I'm sorry.
