### ISSUE TITLE
Move `docs` out of master to `gh-pages` branch

### ISSUE THREAD

**Issue by matrinox** [senorprogrammer/wtf#63]
This keeps the git history clean for the code base while still letting you host on GitHub pages. The main downside is that you'll need to manually synchronize it.

**Comment by senorprogrammer** [comment]
Thanks for the comment. I personally like them in `docs` because I don't mind having that dir in `master` and documentation commits intermingled. To me the documentation is as much a part of the source code as the compilable code and if anyone makes changes to the code that should be reflected in the docs, they shouldn't have to jump into a separate branch and make a separate commit (or set of commits) to do so.
