### ISSUE TITLE
Add Homebrew installation option

### ISSUE THREAD

**Issue by benswinburne** [senorprogrammer/wtf#79]
It'd be great if this could be installed using Homebrew on a mac!

Cheers

**Comment by senorprogrammer** [comment]
Agreed, but it's still a long way from being ready for that.

**Comment by senorprogrammer** [comment]
Closing this issue because Homebrew integration is largely out of my hands. Hopefully one day it will be popular enough to warrant that.

**Comment by rpearce** [comment]
@senorprogrammer thanks for making this! At ~4,000 GH stars right now, do you think it's popular enough to warrant going down the Homebrew path?

**Comment by therealklanni** [comment]
> Homebrew integration is largely out of my hands

Not sure I understand.

Are you not planning to publish to Homebrew, or just "not right now" (unless it gets popular enough)?

If it helps, [this script](https://github.com/rbenv/ruby-build/blob/master/script/brew-publish) makes Homebrew publishing a little easier.

**Comment by senorprogrammer** [comment]
I'm not actively pushing to have it in there yet because under the "Acceptable Formulae" guidelines:

* "Formulae in the core repository must have a stable version tagged" - I don't consider WTF stable at the moment. It's undergoing major flux and undoubtedly some of that will be breaking changes
* "The software in question must be known" - it's been pretty popular the past two weeks but I don't yet know that that will continue
* "We frown on authors submitting their own work" - and I agree with that. Who am I to say it's worth having in there?

Finally, with all the PRs and issues that have been opened recently, and the internal improvements I want to make, also maintaining a Homebrew recipe is _really_ low on my list of priorities and interests at this time (frankly I'd rather finish my FitBit module)

So that's why _I_ haven't pushed for it. However, if someone else wanted to take on that task, I would fully support them.

**Comment by therealklanni** [comment]
Makes sense, thanks!

**Comment by michelegera** [comment]
Hi and thanks for this amazing tool!

Since I love it so much and my dotfiles depend heavily on Homebrew, I went ahead and submitted a PR to `homebrew-cask` (Homebrew/homebrew-cask#59525) for the binary version.

**Comment by senorprogrammer** [comment]
That's fantastic @michelegera, thanks for doing that!

**Comment by michelegera** [comment]
No problem, @senorprogrammer!

Turns out the PR was (rightfully) closed and I was asked to submit another to [Homebrew/core](https://github.com/homebrew/homebrew-core) as a formula that builds from source.

I’d be more than happy to give it a shot, but since my current knowledge of Go and its toolchain is basically zero, I might need a little help 😄 

To be honest, I _did_ make an attempt yesterday and I got something working (using [this gist](https://gist.github.com/miguelmota/33489af6d1655188869f3698020354c3) as a blueprint) but the product of the build was always the `dev` version rather than the current one (`0.5.0`) as I’d expect.

**Comment by Seanstoppable** [comment]
I have experience with brew formulae and am happy to help @michelegera

**Comment by michelegera** [comment]
Thanks @Seanstoppable!

[This is the commit](https://github.com/michelegera/homebrew-core/commit/f95cbe899450ff45417bc022869bd8fef53bb4ae) that adds the formula.

Everything seems to work well, except that the test is not passing since `wtf -v` always outputs `dev`, rather than the expected `0.5.0`, and I’m not sure if this is an issue with my formula or with the code.

Any help would be greatly appreciated!

**Comment by Seanstoppable** [comment]
I think all builds of `wtf` will actually have printed `dev`, if I am looking at history correctly.

Using your formula seems to do the right thing!

**Comment by michelegera** [comment]
So, when building from source the version flag will report `dev` as per [this code](https://github.com/wtfutil/wtf/blob/211bb6b2f0e4d766baba83e7badaaddd62eba536/main.go#L75-L79).

The binaries correctly report `0.5.0` because version is set at compile time by [this line](https://github.com/wtfutil/wtf/blob/ab0dde5169979380f6482a723a02137326412284/Makefile#L27) – `git describe --always --abbrev=6` will return the tag of the commit.

However, I am assuming this only works when building from a clone of the repo, not from [the archive](
https://github.com/wtfutil/wtf/archive/0.5.0.tar.gz) referred by the formula.

@senorprogrammer is that correct? Would it be possible to set the version number at build time from a different source (eg. a `VERSION` file) so that building from the archive sets the correct value?

**Comment by michelegera** [comment]
I tried [a different approach](https://github.com/michelegera/homebrew-core/commit/ae78c85ce6745be7a4e52a5119cda2dcbceca2cc#diff-cf4568cb40149ca9da6e29daf6a621ddR8) and the formula builds, but still reports `dev` as its version 🤔

**Comment by senorprogrammer** [comment]
Yeah, you're right. If you're calling something like `go run main.go -v` it'll always return `dev` because the actual version is inlined at compile time. I like the idea of a `VERSION` file as a better alternative.

**Comment by michelegera** [comment]
@senorprogrammer that’s great! When that’s ready, I will update my branch and open a PR to homebrew-core.
